### ISSUE TITLE
Can't download sitemap generated

### ISSUE THREAD

**Issue by MihaelN** [madchops1/sitemap-generator#1]
I have a website created in Angular 4. When crawling, it recognises url's but when it finishes download is not starting even tho' in the console log I can see this:

download 9scripts.5c94af11.js:1

Screen flashes for a split second but nothing happens.
Browser is Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by seunggs** [comment]
I'm getting a blank page open on clicking download button as well.

**Comment by madchops1** [comment]
Fixed!
