### ISSUE TITLE
Botmap.io is down

### ISSUE THREAD

**Issue by adyry** [madchops1/sitemap-generator#12]
Your super crawler is down, any chances bringing it up again?

403 Forbidden
Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: A43FE6ED196E4528
HostId: T4OTrDWVfVWIl/SP8coAp/9o6ObPXFSS8YSiKNYBvbh0Zwhf9wElVbm5H9bHQmix8dDjNsovuzQ=

**Comment by madchops1** [comment]
Ya it will be back soon. I am having trouble paying for my AWS :(

**Comment by madchops1** [comment]
its up, for at least the rest of the month

**Comment by pablo67340** [comment]
The website is down again, would you like to host this on my server for free? This is a tool a ton of people used and I am sure its not just me missing it </3

**Comment by binaryhq** [comment]
again?

**Comment by domhacking** [comment]
Happy to donate to help it stay up and running

**Comment by madchops1** [comment]
I have it back up at botmap.surge.sh
